<?php

/**
 * @var $block \HK2\AddBootstrap5\Block\Index
 */

$is_enabled = $block->isEnabled();

if ($is_enabled) {
    $bootstrap_version = $block->getBootstrapVersion();
    $link = $block->generateBootstrapCdnLink($bootstrap_version);

    /* @noEscape */
    echo PHP_EOL . PHP_EOL . '<!-- HK2 Bootstrap CSS Style START -->' . PHP_EOL;
    echo  $link["style"];
    echo PHP_EOL . '<!-- HK2 Bootstrap CSS Style ENDS -->' . PHP_EOL;
}
